[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cmds = [
    "python -m pip install -r requirements.txt",
    "cd react-frontend && npm install && npm run build",
    "mkdir -p frontend_build",
    "cp -r react-frontend/dist/* frontend_build/"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"
